// GENERATED by scripts/measure-figure-heights.py — do NOT hand-edit.
// Re-run the script whenever a companion/skin is added or its art changes.
// `fill` = opaque-content height and `pad` = content-bottom gap, both as
// fractions of the square render box (contentFit: "contain"). Consumed by
// src/lib/figure-height.ts to equalize figure heights in the study room.
export const FIGURE_METRICS: Record<string, { fill: number; pad: number }> = {
  'bun/classic': { fill: 0.9035, pad: 0.0781 },
  'bun/heartcore': { fill: 0.9043, pad: 0.0774 },
  'bun/starry': { fill: 0.9082, pad: 0.0342 },
  'companion_bunny/classic': { fill: 0.8424, pad: 0.0508 },
  'companion_bunny/jiraikei': { fill: 0.8047, pad: 0.0508 },
  'companion_bunny/palace': { fill: 0.9271, pad: 0.0508 },
  'companion_bunny/royal': { fill: 0.8880, pad: 0.0495 },
  'companion_cocoa/classic': { fill: 0.8876, pad: 0.0598 },
  'companion_cocoa/demon': { fill: 0.8892, pad: 0.0606 },
  'companion_cocoa/relax': { fill: 0.8349, pad: 0.0606 },
  'companion_honey/champion': { fill: 0.8174, pad: 0.0247 },
  'companion_honey/classic': { fill: 0.9482, pad: 0.0343 },
  'companion_honey/zzz': { fill: 0.8541, pad: 0.0335 },
  'companion_pretzel/classic': { fill: 0.9314, pad: 0.0247 },
  'companion_tira/afternoontrain': { fill: 0.8190, pad: 0.0495 },
  'companion_tira/chocomint': { fill: 0.9082, pad: 0.0342 },
  'companion_tira/classic': { fill: 0.8919, pad: 0.0508 },
  'companion_tira/sleepover': { fill: 0.9082, pad: 0.0342 },
  'hanji/classic': { fill: 0.8692, pad: 0.0582 },
  'hanji/ivoryrose': { fill: 0.9871, pad: 0.0060 },
};
