// GENERATED by scripts/measure-figure-heights.py — do NOT hand-edit.
// Re-run the script whenever a companion/skin is added or its art changes.
// `fill` = opaque-content height and `pad` = content-bottom gap, both as
// fractions of the square render box (contentFit: "contain"). Consumed by
// src/lib/figure-height.ts to equalize figure heights in the study room.
export const FIGURE_METRICS: Record<string, { fill: number; pad: number }> = {
  'bun/angel': { fill: 0.8605, pad: 0.0706 },
  'bun/classic': { fill: 0.8317, pad: 0.0758 },
  'bun/dreams': { fill: 0.8644, pad: 0.0550 },
  'bun/snowrabbit': { fill: 0.8309, pad: 0.0766 },
  'bun/strawberry': { fill: 0.7974, pad: 0.0766 },
  'companion_bunny/classic': { fill: 0.8939, pad: 0.0502 },
  'companion_bunny/jiraikei': { fill: 0.8190, pad: 0.0750 },
  'companion_bunny/palace': { fill: 0.9370, pad: 0.0407 },
  'companion_cocoa/classic': { fill: 0.8876, pad: 0.0598 },
  'companion_cocoa/demon': { fill: 0.8892, pad: 0.0606 },
  'companion_cocoa/relax': { fill: 0.8349, pad: 0.0606 },
  'companion_honey/champion': { fill: 0.8325, pad: 0.0845 },
  'companion_honey/classic': { fill: 0.9537, pad: 0.0255 },
  'companion_honey/zzz': { fill: 0.8644, pad: 0.0526 },
  'companion_tira/afternoontrain': { fill: 0.8788, pad: 0.0502 },
  'companion_tira/chocomint': { fill: 0.8828, pad: 0.0423 },
  'companion_tira/classic': { fill: 0.8788, pad: 0.0502 },
  'companion_tira/sleepover': { fill: 0.8796, pad: 0.0494 },
  'hanji/classic': { fill: 0.8692, pad: 0.0582 },
  'hanji/ivoryrose': { fill: 0.9871, pad: 0.0060 },
};
