#!/usr/bin/env python3
"""
Measure every companion/skin figure PNG and generate src/constants/figure-calibration.ts.

Run from the repo root:  python3 scripts/measure-figure-heights.py
Re-run whenever a companion or wardrobe skin is added, or its art changes.

Why
---
Study-room figures all render into ONE shared square box with contentFit:"contain",
but each PNG's opaque content fills a different fraction of its canvas (0.80-0.99),
so characters rendered "the same size" come out visibly different heights — and a
skin swap changes a character's height. src/lib/figure-height.ts fixes that with:

  * FIGURE_METRICS (generated HERE) — per image, `fill` = opaque-content height as
    a fraction of the rendered box, `pad` = gap between the content bottom and the
    box bottom (letterbox-safe for non-square canvases).
  * HEIGHT_LADDER (hand-tuned, in figure-height.ts) — each companion's height
    relative to Bunny.

The image list is discovered from BUN_SKINS + COMPANION_SKINS in
src/lib/companion-utils.ts, so new skins are picked up automatically. Special case:
hanji/classic renders the animated HanjiFigure whose base layer is hanji-body.png
(the flat hanji.png never shows in the study room), so that file is measured.
"""
import os
import re

from PIL import Image
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UTILS_TS = os.path.join(ROOT, 'src', 'lib', 'companion-utils.ts')
OUT_TS = os.path.join(ROOT, 'src', 'constants', 'figure-calibration.ts')

# hanji/classic = animated HanjiFigure; its height comes from the body layer.
HANJI_CLASSIC_ART = 'assets/images/hanji/hanji-body.png'

# One skin entry inside a skins array: pair each `id: '<skin>'` with the entry's
# `require('@/<asset>')` that follows it (the image comes before the lore text,
# so non-greedy matching can't jump entries).
ENTRY_RE = re.compile(r"(?<!\w)id: '([^']+)'.*?require\('@/(assets/images/[^']+)'\)", re.S)


def discover_images() -> dict[str, str]:
    """Figure key ('<companion>/<skin>') -> repo-relative PNG path."""
    src = open(UTILS_TS, encoding='utf-8').read()
    images: dict[str, str] = {}

    bun_block = re.search(r'export const BUN_SKINS[^=]*= \[(.*?)\n\];', src, re.S).group(1)
    for skin_id, path in ENTRY_RE.findall(bun_block):
        images[f'bun/{skin_id}'] = path

    comp_block = re.search(r'export const COMPANION_SKINS[^=]*= \{(.*?)\n\};', src, re.S).group(1)
    # Split the record into per-companion chunks on the `'shop:<itemId>': [` keys.
    parts = re.split(r"'shop:(\w+)': \[", comp_block)
    for item_id, chunk in zip(parts[1::2], parts[2::2]):
        # Same key convention as SOLO_BOOK_OFFSET / HEIGHT_LADDER: shop item id,
        # except Hanji which is keyed plain 'hanji'.
        key = 'hanji' if item_id == 'companion_hanji' else item_id
        for skin_id, path in ENTRY_RE.findall(chunk):
            images[f'{key}/{skin_id}'] = path

    images['hanji/classic'] = HANJI_CLASSIC_ART
    return images


def measure(path: str) -> tuple[float, float]:
    """(fill, pad) of a PNG contain-fitted into a square box, as box fractions."""
    im = Image.open(os.path.join(ROOT, path)).convert('RGBA')
    a = np.asarray(im)
    w, h = im.size
    ys = np.where(a[:, :, 3] > 30)[0]  # opaque rows
    y0, y1 = int(ys.min()), int(ys.max())
    s = min(1.0 / w, 1.0 / h)  # box fraction per source px (contentFit: contain)
    fill = (y1 - y0 + 1) * s
    pad = (h - 1 - y1) * s + (1 - h * s) / 2  # bottom gap + letterbox margin
    return fill, pad


def main() -> None:
    images = discover_images()
    lines = [
        '// GENERATED by scripts/measure-figure-heights.py — do NOT hand-edit.',
        '// Re-run the script whenever a companion/skin is added or its art changes.',
        '// `fill` = opaque-content height and `pad` = content-bottom gap, both as',
        '// fractions of the square render box (contentFit: "contain"). Consumed by',
        '// src/lib/figure-height.ts to equalize figure heights in the study room.',
        'export const FIGURE_METRICS: Record<string, { fill: number; pad: number }> = {',
    ]
    for key in sorted(images):
        fill, pad = measure(images[key])
        lines.append(f"  '{key}': {{ fill: {fill:.4f}, pad: {pad:.4f} }},")
    lines.append('};')
    lines.append('')

    with open(OUT_TS, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f'Wrote {len(images)} entries to {os.path.relpath(OUT_TS, ROOT)}')


if __name__ == '__main__':
    main()
